### PR TITLE
Add some descriptions and link to CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by shapkarin**

### CODE REVIEW

**Comment by shapkarin** [comment]
@koolamusic OK i'll remove ./CONTRIBUTING.md and add link README.md with existing

**Comment by shapkarin** [comment]
I also changed yours CONTRIBUTING.md

**Comment by shapkarin** [comment]
@koolamusic I'm not sure that I understand you currently, because https://github.com/koolamusic/awesome-imba/blob/master/.github/CONTRIBUTING.md is just like in link that I send https://github.com/sindresorhus/awesome/blob/master/code-of-conduct.md

**Comment by koolamusic** [comment]
I will take a close look, and make an update

**Pull request merged**
