### PR TITLE
Prettify

### PR DESCRIPTION
**Pull request by shapkarin**
Hello. I made some changes. Hope that soon I will provide some new as well.

can't find instructions for `Hello World Imba` #47 I remember that I saw it
Also I'm still not sure about `core tools` seems that it's some kind of useless but it's also nice to list that features.

### CODE REVIEW

**Comment by shapkarin** [comment]
I start to add `Guides and Tutorials` section. And I also found that `Screencasts` are also `Guides and Tutorials` and move them to the `Guides and Tutorials`
I also think to remove `External Resources` section and leave `Articles` in just `Resources`.
Does anyone think that we need to keep `External Resources` and(or) `Screencasts`?

**Comment by koolamusic** [comment]
Noted, will go through this and merge

**Comment by shapkarin** [comment]
comment just to ref this with that issue https://github.com/sindresorhus/awesome/pull/1591 as well

**Comment by shapkarin** [comment]
@koolamusic thanks for replay. Please, use `squash and merge` - don't like if we have all that commits in master.

**Comment by shapkarin** [comment]
@koolamusic and also happy independence day

**Comment by shapkarin** [comment]
hm, seems that squashing makes that commit as yours.. ok, just merge that as usual to track commits 🙌

**Comment by shapkarin** [comment]
not sure about all that squashing side effects I mentioned  and I will check that later.
but thanks anyway 😃

**Pull request merged**
